version: '3'
services:
  db:
    image: postgres:9.6-alpine

  app:
    build: .
    ports:
      - 8081:8081
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=
      - DB_PORT=
      - DB_NAME=postgres
      - DB_SSLMODE=disable
      - APP_PORT=8081
